# Generated by Django 3.0 on 2019-06-11 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accident_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationID', models.IntegerField()),
                ('tableID', models.IntegerField()),
                ('accident_verify', models.CharField(max_length=200)),
                ('state', models.BooleanField()),
                ('compensation_money', models.IntegerField()),
            ],
            options={
                'db_table': 'accident_Application',
            },
        ),
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('userID', models.IntegerField()),
                ('style', models.IntegerField()),
                ('birth', models.DateTimeField(auto_now=True)),
                ('sex', models.BooleanField()),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='applicant_real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'applicant_real',
            },
        ),
        migrations.CreateModel(
            name='compensate_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensateID', models.IntegerField()),
                ('tableID', models.IntegerField()),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('changeTime', models.DateTimeField(auto_now=True)),
                ('changerID', models.IntegerField()),
                ('content', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'compensate_Records',
            },
        ),
        migrations.CreateModel(
            name='complainInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('state', models.BooleanField()),
                ('changerID', models.IntegerField()),
                ('Return', models.CharField(max_length=60)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('changeTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'complainInfor',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsID', models.IntegerField()),
                ('productsName', models.CharField(max_length=30)),
                ('productsStyle', models.CharField(max_length=30)),
                ('productsDes', models.CharField(max_length=60)),
                ('group', models.IntegerField()),
                ('dealCount', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsID', models.IntegerField()),
                ('deadline', models.CharField(max_length=30)),
                ('oneReturen', models.IntegerField()),
                ('weekReturen', models.IntegerField()),
                ('monthReturn', models.IntegerField()),
            ],
            options={
                'db_table': 'profit',
            },
        ),
        migrations.CreateModel(
            name='realtionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('recognizee_ID', models.IntegerField()),
            ],
            options={
                'db_table': 'realtionship',
            },
        ),
        migrations.CreateModel(
            name='recognizee_Infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'recognizee_Infor',
            },
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableID', models.IntegerField()),
                ('productsID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('recognizee_name', models.CharField(max_length=30)),
                ('recognizee_ID', models.IntegerField()),
                ('effectDate', models.DateTimeField(auto_now=True)),
                ('loseDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('payCycle', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('relationship', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='trade_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeID', models.IntegerField()),
                ('tableID', models.IntegerField()),
                ('trade_money', models.IntegerField()),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('changeTime', models.DateTimeField(auto_now=True)),
                ('changerID', models.IntegerField()),
                ('content', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'trade_Records',
            },
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('power', models.IntegerField()),
                ('userID', models.IntegerField()),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
    ]
