# Generated by Django 2.2.2 on 2019-06-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade_records',
            name='changeTime',
        ),
        migrations.RemoveField(
            model_name='trade_records',
            name='changerID',
        ),
        migrations.RemoveField(
            model_name='trade_records',
            name='content',
        ),
    ]
