# Generated by Django 2.2.2 on 2019-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_records',
            name='trade_money',
            field=models.CharField(max_length=30),
        ),
    ]
