# Generated by Django 3.0 on 2019-06-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_accident_application_applicant_applicant_real_compensate_records_complaininfor_img_information_produ'),
    ]

    operations = [
    ]
