# Generated by Django 3.0 on 2019-06-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190611_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apllicant_real',
        ),
        migrations.DeleteModel(
            name='applicant',
        ),
        migrations.DeleteModel(
            name='complainInfor',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='profit',
        ),
        migrations.DeleteModel(
            name='realtionship',
        ),
        migrations.DeleteModel(
            name='recognizee_Infor',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.DeleteModel(
            name='trade_Records',
        ),
        migrations.DeleteModel(
            name='use_login',
        ),
    ]
