# Generated by Django 3.0 on 2019-06-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190611_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accident_Application',
        ),
    ]
