# Generated by Django 2.2.2 on 2019-06-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190622_1605'),
    ]

    operations = [
    ]
