# Generated by Django 2.2.2 on 2019-06-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190622_2038'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table=None,
        ),
    ]
