# Generated by Django 2.2.2 on 2019-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20190613_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_records',
            name='tableID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
