# Generated by Django 3.0 on 2019-06-11 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_accident_application_apllicant_real_applicant_complaininfor_products_profit_realtionship_recognizee_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apllicant_real',
        ),
        migrations.DeleteModel(
            name='applicant',
        ),
        migrations.DeleteModel(
            name='complainInfor',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='profit',
        ),
        migrations.DeleteModel(
            name='realtionship',
        ),
        migrations.DeleteModel(
            name='recognizee_Infor',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.DeleteModel(
            name='trade_Records',
        ),
        migrations.DeleteModel(
            name='use_login',
        ),
        migrations.AlterField(
            model_name='compensate_records',
            name='changeTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compensate_records',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
