# Generated by Django 2.2.2 on 2019-06-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20190622_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='realtionship',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
