# Generated by Django 3.0 on 2019-06-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20190611_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compensate_Records',
        ),
    ]
