# Generated by Django 3.0 on 2019-06-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20190613_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='applicant_real',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='recognizee_infor',
            name='sex',
        ),
    ]
