# Generated by Django 2.2.2 on 2019-06-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20190622_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='realtionship',
        ),
    ]
