# Generated by Django 2.2.2 on 2019-06-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_table_realtionship'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table=None,
        ),
    ]
