# Generated by Django 2.2.2 on 2019-06-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20190622_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
