# Generated by Django 3.0 on 2019-06-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_table_tableid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productsID',
        ),
    ]
