# Generated by Django 3.0 on 2019-06-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20190611_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apllicant_real',
            old_name='ID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='realtionship',
            old_name='ID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='recognizee_infor',
            old_name='ID',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='ID',
        ),
    ]
