# Generated by Django 2.2.2 on 2019-06-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20190622_2057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table=None,
        ),
    ]
