# Generated by Django 3.0 on 2019-06-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20190614_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='userID',
        ),
    ]
