# Generated by Django 3.0 on 2019-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20190611_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apllicant_real',
            new_name='applicant_real',
        ),
        migrations.RenameModel(
            old_name='use_login',
            new_name='user_login',
        ),
        migrations.AlterModelTable(
            name='accident_application',
            table='accident_Application',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='applicant',
        ),
        migrations.AlterModelTable(
            name='applicant_real',
            table='applicant_real',
        ),
        migrations.AlterModelTable(
            name='compensate_records',
            table='compensate_Records',
        ),
        migrations.AlterModelTable(
            name='complaininfor',
            table='complainInfor',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
        migrations.AlterModelTable(
            name='profit',
            table='profit',
        ),
        migrations.AlterModelTable(
            name='realtionship',
            table='realtionship',
        ),
        migrations.AlterModelTable(
            name='recognizee_infor',
            table='recognizee_Infor',
        ),
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
        migrations.AlterModelTable(
            name='trade_records',
            table='trade_Records',
        ),
        migrations.AlterModelTable(
            name='user_login',
            table='user_login',
        ),
    ]
