# Generated by Django 3.0 on 2019-06-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20190622_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensate_records',
            name='userid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
