# Generated by Django 2.2.2 on 2019-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_remove_user_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='telephone',
            field=models.IntegerField(unique=True),
        ),
    ]
