# Generated by Django 2.2.2 on 2019-06-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='company',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='telephone',
        ),
    ]
