# Generated by Django 3.0 on 2019-06-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_compensate_records_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident_application',
            name='image',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
