# Generated by Django 2.2.2 on 2019-06-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_accident_application_image'),
    ]

    operations = [
    ]
