# Generated by Django 3.0 on 2019-06-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_remove_applicant_real_age'),
        ('message', '0012_auto_20190618_1724'),
    ]

    operations = [
    ]
