# Generated by Django 3.0 on 2019-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_merge_20190620_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
