# Generated by Django 3.0 on 2019-06-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_auto_20190623_1836'),
    ]

    operations = [
    ]
