# Generated by Django 3.0 on 2019-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_auto_20190621_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='idcard',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
