# Generated by Django 2.2.2 on 2019-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_applicant_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='userID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaininfor',
            name='user_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recognizee_infor',
            name='userID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='table',
            name='userID',
            field=models.CharField(max_length=30),
        ),
    ]
