# Generated by Django 3.0 on 2019-06-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20190623_1710'),
        ('message', '0019_auto_20190623_2003'),
    ]

    operations = [
    ]
