# Generated by Django 3.0 on 2019-06-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_merge_20190623_2319'),
    ]

    operations = [
    ]
