# Generated by Django 2.2.2 on 2019-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_complaininfor_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaininfor',
            name='changerID',
            field=models.CharField(max_length=30),
        ),
    ]
