# Generated by Django 3.0 on 2019-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_auto_20190623_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login',
            name='changeTime',
        ),
        migrations.AddField(
            model_name='table',
            name='education_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
