# Generated by Django 2.2.2 on 2019-06-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_auto_20190621_2217'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
    ]
