# Generated by Django 3.0 on 2019-06-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0022_auto_20190623_2326'),
    ]

    operations = [
    ]
