# Generated by Django 3.0 on 2019-06-22 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0023_user_login_changetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaininfor',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
