# Generated by Django 3.0 on 2019-06-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0024_auto_20190623_2328'),
    ]

    operations = [
    ]
