# Generated by Django 3.0 on 2019-06-22 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0024_auto_20190622_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensate_records',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='table',
            name='loseDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='trade_records',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='changeTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
