# Generated by Django 3.0 on 2019-06-23 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0026_auto_20190623_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='changeTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
