# Generated by Django 3.0 on 2019-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0026_remove_recognizee_infor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtionship',
            name='recognizee_ID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='realtionship',
            name='userID',
            field=models.CharField(max_length=30),
        ),
    ]
