# Generated by Django 3.0 on 2019-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0027_auto_20190622_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtionship',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
