# Generated by Django 3.0 on 2019-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0027_user_login_changetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident_application',
            name='image_src',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='Returen',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='deadLine',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='payMethod',
        ),
        migrations.RemoveField(
            model_name='table',
            name='education_money',
        ),
        migrations.AddField(
            model_name='profit',
            name='deadline',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='monthReturn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='oneReturen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='weekReturen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
