# Generated by Django 3.0 on 2019-06-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0028_realtionship_createtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtionship',
            name='createTime',
        ),
    ]
