# Generated by Django 3.0 on 2019-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0029_remove_realtionship_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='idcard',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant_real',
            name='userID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='recognizee_infor',
            name='userID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='recognizee_ID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
