# Generated by Django 3.0 on 2019-06-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0029_accident_application_image_src'),
    ]

    operations = [
    ]
