# Generated by Django 3.0 on 2019-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0030_auto_20190623_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='monthReturn',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='oneReturen',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='weekReturen',
        ),
        migrations.AddField(
            model_name='profit',
            name='Returen',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='deadLine',
            field=models.SmallIntegerField(choices=[(3, '交3年'), (5, '交5年'), (18, '交至18岁')], default=1, verbose_name='交费年限'),
        ),
        migrations.AddField(
            model_name='profit',
            name='payMethod',
            field=models.SmallIntegerField(choices=[(0, 'week'), (1, 'month'), (2, 'one time')], default=1, verbose_name='交费方式'),
        ),
        migrations.AddField(
            model_name='table',
            name='education_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
