# Generated by Django 3.0 on 2019-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0031_auto_20190623_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='dealCount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productsStyle',
        ),
        migrations.RemoveField(
            model_name='products',
            name='recognizee_age_range',
        ),
        migrations.AddField(
            model_name='products',
            name='applicant_range_age',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='money_range',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='payMethod',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='payRange',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='productID',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='recog_range_age',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='time_range',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
