# Generated by Django 3.0 on 2019-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0032_auto_20190624_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='money',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
