# Generated by Django 3.0 on 2019-06-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0038_auto_20190624_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensate_records',
            name='changeTime',
        ),
        migrations.RemoveField(
            model_name='compensate_records',
            name='changerID',
        ),
        migrations.RemoveField(
            model_name='compensate_records',
            name='compensateID',
        ),
        migrations.RemoveField(
            model_name='compensate_records',
            name='content',
        ),
    ]
